### ISSUE TITLE
[WIP] TODO for alpha release

### ISSUE THREAD

**Issue by luomai** [quiver-team/torch-quiver#58]
- [x] 1 example for PyG, and 1 example for DGL.
- [x] Pip install: `pip install torch-quiver`
- [x] Unit Tests
- [x] Documents (API design, and design principles)
- [x] Performance numbers (papers100M dataset)
- [x] README (Features, Install, Toy Example, APIs for PyG and DGL, ...)
- [x] Community name: quiver-team
- [x] Library name: `torch-quiver`
- [x] Docker image
