### ISSUE TITLE
TODO for 0.2.0 Release

### ISSUE THREAD

**Issue by ZenoTan** [quiver-team/torch-quiver#65]
- [x] Hybrid sampling support @eedalong #93 
- [x] Distributed design and benchmark (240M) @eedalong @ZenoTan #108 
- [x] Adaptive ~~computation~~ and data allocation #103
- [x] More Quiver examples @lausannel #82 
- [x] Fix device topology configuration @ZenoTan @eedalong 
- [ ] Add documents for distributed training
